upstream app{
    server app-1:8000;
    server app-2:8000;
}


server {
    listen 80;

    # Serve static UI files
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        proxy_pass http://app/;
        proxy_set_header Host $host;
    }
}
